### ISSUE TITLE
Allow for changing swap file size and path

### ISSUE THREAD

**Issue by colin-byrne-1** [weareinteractive/ansible-swap#1]
I will try to do this, don't have the time at the moment, but it would be pretty sweet if we could build in functionality for changing the swap file size and path once it has already been set. Thanks for the helpful role, though.

**Comment by franklinkim** [comment]
hi, yeah, will look into it. thought i gonna need that my self sooner but since i didn't I kinda left that open...

**Comment by franklinkim** [comment]
hi, I added the possibility to change the size.
**Note:** you need to define the size in bytes now.

To change the location of the file would require some more logic that I think would better be suited in a module rather than a role.
